name: Token Push Pipeline

on:
  push:
    branches:
      - main

jobs:
  token_push_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Navigate to TokenParser directory
        working-directory: ./front-custom-packages-main
        run: npm install

      - name: Run token parser
        working-directory: ./front-custom-packages-main
        run: npm run generate-token-test

      - name: Set Git user info
        run: |
          git config --global user.email "kuznietsovalex@gmail.com"
          git config --global user.name "Silescream"

        
      - name: Add generated files to Git
        working-directory: ./front-custom-packages-main
        run: |
          git add themes/*
          git commit -m "Add generated CSS files from tokens"
          git push
